"""Strongly typed input and output models for the Schema Validation Agent."""

from typing import Any

from pydantic import BaseModel, Field


class AgentFinding(BaseModel):
    """Aggregated schema validation finding."""

    category: str = Field(..., description="The validation category or skill name.")
    severity: str = Field(..., description="Severity level: low, medium, or high.")
    description: str = Field(
        ..., description="Description of the pattern or issue found."
    )
    suggestion: str | None = Field(
        default=None, description="Suggested action to address this finding."
    )


class ExecutiveSummaryResponse(BaseModel):
    """Structured response containing only the generated summary text."""

    summary: str = Field(
        ..., description="Concise executive summary of the aggregated findings."
    )


class SchemaValidationReport(BaseModel):
    """The unified schema validation report generated by the agent."""

    overall_status: str = Field(
        ..., description="Overall report status: pass, fail, or warning."
    )
    summary: str = Field(
        ..., description="Executive summary generated by the aggregator."
    )
    findings: list[AgentFinding] = Field(
        default_factory=list,
        description="Deduplicated, severity-sorted validation findings.",
    )
    recommendations: list[str] = Field(
        default_factory=list, description="Actionable schema design recommendations."
    )
    warnings: list[str] = Field(
        default_factory=list, description="Any system or execution-level warnings."
    )
    execution_statistics: dict[str, Any] = Field(
        default_factory=dict,
        description="Execution metrics per skill (latency, success).",
    )
    executed_skills: list[str] = Field(
        default_factory=list, description="Names of the executed skills."
    )
    execution_duration_ms: float = Field(
        ..., description="Total agent execution duration in milliseconds."
    )
