"""Execution plan and cost estimation schemas for the Guardian Planner."""

from pydantic import BaseModel, Field


class ExecutionCostEstimate(BaseModel):
    """Deterministic cost estimation metrics for schema synthetic data generation."""

    estimated_duration_seconds: float = Field(
        ..., description="Estimated total generation duration in seconds."
    )
    estimated_memory_mb: float = Field(
        ..., description="Estimated memory consumption in MB."
    )
    estimated_cpu_weight: float = Field(
        ..., description="Estimated virtual CPU weight score (0.1 to 10.0)."
    )
    estimated_io_weight: float = Field(
        ..., description="Estimated virtual I/O weight score (0.1 to 100.0)."
    )
    estimated_complexity_score: float = Field(
        ..., description="Heuristic complexity score."
    )
    estimated_parallelism: int = Field(
        ..., description="Estimated maximum parallelism degree."
    )
    estimated_llm_calls: int = Field(
        ..., description="Estimated number of LLM API requests."
    )
    estimated_llm_cost: float = Field(
        ..., description="Estimated cost of LLM calls in USD."
    )
    confidence: float = Field(
        ..., description="Heuristic planning confidence score (0.0 to 1.0)."
    )


class PlanningStatistics(BaseModel):
    """Statistics about the database schema structure and planning outcomes."""

    table_count: int = Field(..., description="Number of tables in the schema.")
    relationship_count: int = Field(
        ..., description="Number of foreign key relationships."
    )
    dependency_depth: int = Field(
        ..., description="Maximum dependency depth (number of execution groups)."
    )
    execution_groups: int = Field(..., description="Number of execution groups.")
    independent_groups: int = Field(
        ..., description="Number of independent tables (level 0)."
    )
    cyclic_dependencies_detected: bool = Field(
        ..., description="Flag indicating if a cyclic dependency was found."
    )
    isolated_tables: list[str] = Field(
        ..., description="List of tables with zero incoming or outgoing dependencies."
    )


class ExecutionPlan(BaseModel):
    """The execution plan generated by the Guardian Planner."""

    execution_id: str = Field(
        ..., description="UUID identifying this specific execution plan."
    )
    schema_hash: str = Field(
        ..., description="SHA-256 hash of the target database schema DDL."
    )
    execution_groups: list[list[str]] = Field(
        ...,
        description="Independent execution layers of table names for parallel generation.",
    )
    ordered_tables: list[str] = Field(
        ..., description="Topologically sorted list of all tables."
    )
    dependency_levels: dict[str, int] = Field(
        ..., description="Depth level index per table name."
    )
    estimated_complexity: str = Field(
        ..., description="Estimated layout complexity level: low, medium, or high."
    )
    estimated_execution_time: float = Field(
        ..., description="Estimated synthetic data generation time in seconds."
    )
    warnings: list[str] = Field(
        default_factory=list,
        description="List of warnings or issues identified during planning.",
    )
    planner_version: str = Field(
        ..., description="Semantic version string of this planner execution."
    )
    generated_at: str = Field(
        ..., description="Timestamp of when this plan was created."
    )

    # Extended metadata fields
    estimated_total_duration: float = Field(
        ...,
        description="Heuristic estimate of the total generation duration in seconds.",
    )
    estimated_peak_memory: float = Field(
        ..., description="Heuristic estimate of the peak memory usage in MB."
    )
    estimated_parallel_workers: int = Field(
        ..., description="Number of workers suggested for parallel execution."
    )
    estimated_llm_cost: float = Field(
        ..., description="Estimated cost of LLM calls in USD."
    )
    estimated_generation_cost: float = Field(
        ..., description="Estimated total cost of the generation process."
    )
    planning_confidence: float = Field(
        ..., description="Heuristic score of planning confidence (0.0 to 1.0)."
    )

    # Linked nested models
    cost_estimate: ExecutionCostEstimate = Field(
        ..., description="Detailed deterministic cost estimation breakdown."
    )
    statistics: PlanningStatistics = Field(
        ..., description="Calculated planning statistics."
    )
