"""add_optimistic_locking_and_indexes

Revision ID: 2c95953f5096
Revises: 13389056f9ba
Create Date: 2026-07-02 16:32:47.868447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c95953f5096'
down_revision: Union[str, Sequence[str], None] = '13389056f9ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.alter_column('key',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_event_type'), ['event_type'], unique=False)

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_project_id'), ['project_id'], unique=False)

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version', sa.Integer(), nullable=False))

    with op.batch_alter_table('schemas', schema=None) as batch_op:
        batch_op.create_index('idx_schema_project_active', ['project_id', 'is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_schemas_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_schemas_project_id'), ['project_id'], unique=False)

    with op.batch_alter_table('validation_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_validation_history_schema_id'), ['schema_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('validation_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_validation_history_schema_id'))

    with op.batch_alter_table('schemas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schemas_project_id'))
        batch_op.drop_index(batch_op.f('ix_schemas_is_active'))
        batch_op.drop_index('idx_schema_project_active')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('version')

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_project_id'))

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_event_type'))

    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.alter_column('key',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###
