"""Metrics Pydantic models representing execution measurements."""

from typing import Any, Literal

from pydantic import BaseModel, Field


class ResourceUsage(BaseModel):
    """Monitored system resources."""

    memory_bytes: int | Literal["Unknown", "Not Yet Measured"] = Field(
        default="Not Yet Measured",
        description="Measured memory usage or placeholder if unmeasured.",
    )
    cpu_percent: float | Literal["Unknown", "Not Yet Measured"] = Field(
        default="Not Yet Measured",
        description="Measured CPU usage or placeholder if unmeasured.",
    )


class ExecutionMetrics(BaseModel):
    """Consolidated performance timings and resource counts for an execution step."""

    duration_ms: float | Literal["Unknown", "Not Yet Measured"] = Field(
        default="Not Yet Measured",
        description="Measured execution duration in milliseconds.",
    )
    resource_usage: ResourceUsage = Field(
        default_factory=ResourceUsage,
        description="System resource usage snapshot.",
    )
    llm_calls: int | Literal["Unknown", "Not Yet Measured"] = Field(
        default="Not Yet Measured",
        description="Number of external language model invocations.",
    )
    prompt_tokens: int | Literal["Unknown", "Not Yet Measured"] = Field(
        default="Not Yet Measured",
        description="Number of prompt tokens sent to language models.",
    )
    completion_tokens: int | Literal["Unknown", "Not Yet Measured"] = Field(
        default="Not Yet Measured",
        description="Number of completion tokens generated by language models.",
    )
    total_tokens: int | Literal["Unknown", "Not Yet Measured"] = Field(
        default="Not Yet Measured",
        description="Total tokens consumed (prompt + completion).",
    )
    llm_cost_usd: float | Literal["Unknown", "Not Yet Measured"] = Field(
        default="Not Yet Measured",
        description="Calculated financial cost in USD.",
    )


class StageMetrics(BaseModel):
    """State and metric details representing a specific stage in the pipeline execution."""

    stage_name: str = Field(
        ..., description="Unique name identifier of the pipeline stage."
    )
    status: str = Field(
        ..., description="Execution outcome state (e.g. pending, completed, failed)."
    )
    metrics: ExecutionMetrics = Field(
        default_factory=ExecutionMetrics,
        description="Consolidated step execution measurements.",
    )
    errors: list[str] = Field(
        default_factory=list,
        description="Detail of critical execution error messages.",
    )
    warnings: list[str] = Field(
        default_factory=list,
        description="Detail of non-fatal warnings or violations.",
    )
    metadata: dict[str, Any] = Field(
        default_factory=dict,
        description="Additional contextual metadata.",
    )


class PipelineMetrics(BaseModel):
    """Unified metrics representing the full execution of the data generation pipeline."""

    stages: dict[str, StageMetrics] = Field(
        default_factory=dict,
        description="Mapping of stage name keys to stage performance metrics.",
    )
    total_duration_ms: float | Literal["Unknown", "Not Yet Measured"] = Field(
        default="Not Yet Measured",
        description="Unified duration sum across executed stages.",
    )
    total_records: int | Literal["Unknown", "Not Yet Measured"] = Field(
        default="Not Yet Measured",
        description="Total record count serialized.",
    )
    total_tables: int | Literal["Unknown", "Not Yet Measured"] = Field(
        default="Not Yet Measured",
        description="Total count of database tables exported.",
    )
    total_file_size_bytes: int | Literal["Unknown", "Not Yet Measured"] = Field(
        default="Not Yet Measured",
        description="Total data payload size written to disk.",
    )
