"""JSON parsing engines for cleaning and converting raw LLM provider text responses."""

import json
import re
from typing import Any

from app.llm.contracts.exceptions import AIContractParsingError


def extract_json_payload(text: str) -> str:
    """Extract raw JSON substring from markdown code blocks or clean wrapper formatting.

    Args:
        text: Raw text generated by the LLM.

    Returns:
        str: Cleansed substring containing just the JSON payload.
    """
    text = text.strip()

    # Search for JSON formatted inside markdown code blocks (```json ... ``` or ``` ... ```)
    match = re.search(r"```(?:json)?\s*(.*?)\s*```", text, re.DOTALL | re.IGNORECASE)
    if match:
        return match.group(1).strip()

    return text


def parse_to_dict(text: str) -> dict[str, Any]:
    """Parse raw string response into a dictionary, extracting JSON if wrapped in markdown.

    Args:
        text: Raw response string.

    Returns:
        dict[str, Any]: The decoded JSON object.

    Raises:
        AIContractParsingError: If parsing fails or the input is empty/malformed.
    """
    if not text.strip():
        raise AIContractParsingError("Response content is empty.")

    cleaned_text = extract_json_payload(text)

    try:
        data = json.loads(cleaned_text)
    except json.JSONDecodeError as exc:
        raise AIContractParsingError(f"Malformed JSON payload: {exc}") from exc

    if not isinstance(data, dict):
        raise AIContractParsingError(
            f"Expected JSON object (dict), got {type(data).__name__}"
        )

    return data
