"""Validation logic for LLM response text."""

import json

from app.llm.exceptions import LLMValidationError


def validate_response_text(text: str, json_mode: bool = False) -> None:
    """Validate the response string generated by the LLM provider.

    Args:
        text: Raw response string.
        json_mode: If True, validates that response is valid JSON.

    Raises:
        LLMValidationError: If validation checks fail.
    """
    if not text or not text.strip():
        raise LLMValidationError("LLM provider returned an empty response text.")

    if json_mode:
        # Strip potential markdown code block wrappers
        cleaned = text.strip()
        if cleaned.startswith("```"):
            # Find the starting JSON line and extract JSON content
            lines = cleaned.splitlines()
            if (
                len(lines) >= 3
                and lines[-1].startswith("```")
                and (
                    lines[0].lower().startswith("```json") or lines[0].startswith("```")
                )
            ):
                cleaned = "\n".join(lines[1:-1]).strip()

        try:
            json.loads(cleaned)
        except json.JSONDecodeError as exc:
            raise LLMValidationError(
                f"LLM response failed JSON validation: {exc}. Raw text: {text}"
            ) from exc
