"""Validation logic for LLM response text."""

import json
import re

from app.llm.exceptions import LLMValidationError


def repair_json(text: str) -> str:
    """Attempt basic structural repair on truncated or malformed JSON."""
    cleaned = text.strip()
    if cleaned.startswith("```"):
        lines = cleaned.splitlines()
        if lines[0].lower().startswith("```json") or lines[0].startswith("```"):
            if lines[-1].startswith("```"):
                cleaned = "\n".join(lines[1:-1]).strip()
            else:
                cleaned = "\n".join(lines[1:]).strip()

    # Simple heuristic to close arrays/objects if truncated
    opened_braces = cleaned.count("{") - cleaned.count("}")
    opened_brackets = cleaned.count("[") - cleaned.count("]")

    if cleaned.endswith(",") or cleaned.endswith(",\n"):
        cleaned = cleaned.rstrip(",\n")

    # Remove trailing unclosed string literals
    if cleaned.count('"') % 2 != 0:
        last_quote_idx = cleaned.rfind('"')
        if last_quote_idx != -1:
            cleaned = cleaned[:last_quote_idx].rstrip(", \n")

    # Close structures (handles under-closing)
    for _ in range(opened_braces):
        cleaned += "}"
    for _ in range(opened_brackets):
        cleaned += "]"

    # Handle over-closing: extra } before ] (e.g., }"Male"}}] → }"Male"}])
    return re.sub(r"\}(?=\}\])", "", cleaned)


def validate_response_text(text: str, json_mode: bool = False) -> None:
    """Validate the response string generated by the LLM provider.

    Args:
        text: Raw response string.
        json_mode: If True, validates that response is valid JSON.

    Raises:
        LLMValidationError: If validation checks fail.
    """
    if not text or not text.strip():
        raise LLMValidationError("LLM provider returned an empty response text.")

    if json_mode:
        # Strip potential markdown code block wrappers
        cleaned = text.strip()
        if cleaned.startswith("```"):
            # Find the starting JSON line and extract JSON content
            lines = cleaned.splitlines()
            if (
                len(lines) >= 3
                and lines[-1].startswith("```")
                and (
                    lines[0].lower().startswith("```json") or lines[0].startswith("```")
                )
            ):
                cleaned = "\n".join(lines[1:-1]).strip()

        try:
            json.loads(cleaned)
        except json.JSONDecodeError as exc:
            raise LLMValidationError(
                f"LLM response failed JSON validation: {exc}. Raw text: {text}"
            ) from exc
